package com.hiscat.online.edu.warehouse.bean

import scala.beans.BeanProperty

case class DwsMember(
                      @BeanProperty var uid: Int,
                      @BeanProperty var ad_id: Int,
                      @BeanProperty var fullname: String,
                      @BeanProperty var iconurl: String,
                      @BeanProperty var lastlogin: String,
                      @BeanProperty var mailaddr: String,
                      @BeanProperty var memberlevel: String,
                      @BeanProperty var password: String,
                      @BeanProperty var paymoney: String,
                      @BeanProperty var phone: String,
                      @BeanProperty var qq: String,
                      @BeanProperty var register: String,
                      @BeanProperty var regupdatetime: String,
                      @BeanProperty var unitname: String,
                      @BeanProperty var userip: String,
                      @BeanProperty var zipcode: String,
                      @BeanProperty var appkey: String,
                      @BeanProperty var appregurl: String,
                      @BeanProperty var bdp_uuid: String,
                      @BeanProperty var reg_createtime: String,
                      @BeanProperty var domain: String,
                      @BeanProperty var isranreg: String,
                      @BeanProperty var regsource: String,
                      @BeanProperty var regsourcename: String,
                      @BeanProperty var adname: String,
                      @BeanProperty var siteid: Integer,
                      @BeanProperty var sitename: String,
                      @BeanProperty var siteurl: String,
                      @BeanProperty var site_delete: String,
                      @BeanProperty var site_createtime: String,
                      @BeanProperty var site_creator: String,
                      @BeanProperty var vip_id: Integer,
                      @BeanProperty var vip_level: String,
                      @BeanProperty var vip_start_time: String,
                      @BeanProperty var vip_end_time: String,
                      @BeanProperty var vip_last_modify_time: String,
                      @BeanProperty var vip_max_free: String,
                      @BeanProperty var vip_min_free: String,
                      @BeanProperty var vip_next_level: String,
                      @BeanProperty var vip_operator: String,
                      @BeanProperty var dt: String,
                      @BeanProperty var dn: String
                    )
